export const RABBIT_MQ_QUEUE = 'products_queue';

export enum RabbitMQQueue {
  CREATE_PRODUCTS = 'CREATE_PRODUCTS',
  FIND_ALL_PRODUCTS = 'FIND_ALL_PRODUCTS',
  FIND_PRODUCT_BY_ID = 'FIND_PRODUCT_BY_ID',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
}
